### ISSUE TITLE
It does not run

### ISSUE THREAD

**Issue by marco-eckstein** [Deskbot/Cognitive-Complexity-TS#17]
I just installed it and tried to run it, but it gives me an error:

```
$ npx ccts src/
C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\node-naming.js:216
        throw new node_util_1.UnreachableNodeState(node, "Module has no module/namespace keyword.");
              ^

UnreachableNodeState [Error]: Unreachable branch.
Module has no module/namespace keyword.
At: Window.ts:4:0
    at getModuleDeclarationName (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\node-naming.js:216:15)
    at chooseContainerName (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\node-naming.js:48:16)
    at aggregateCostOfChildren (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\cognitive-complexity.js:47:60)
    at nodeCost (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\cognitive-complexity.js:172:37)
    at aggregateCostOfChildren (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\cognitive-complexity.js:44:27)
    at nodeCost (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\cognitive-complexity.js:172:37)
    at fileCost (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\cognitive-complexity.js:34:12)
    at getSourceOutput (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\output.js:58:48)
    at getFileOutput (C:\Users\Marco\AppData\Roaming\npm\node_modules\cognitive-complexity-ts\build\src\cognitive-complexity\output.js:52:12)
    at async Promise.all (index 13)

Node.js v18.20.4
```

**Comment by marco-eckstein** [comment]
My mistake. Should not have used a folder, but a file path as argument.
